version: '3.8'

services:
  # =============================================================================
  # Development Environment - Single container with all tools
  # =============================================================================
  devcontainer:
    build:
      context: .
      target: development
    container_name: cs2-dev
    volumes:
      - .:/workspace
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspace/target
      - /var/run/docker.sock:/var/run/docker.sock  # Docker-in-Docker access
    ports:
      - "8080:8080"   # API server
      - "8888:8888"   # Jupyter notebook
      - "3000:3000"   # Frontend dev server
      - "9090:9090"   # Prometheus (if needed)
    environment:
      - DATABASE_URL=postgresql://cs2user:cs2pass@postgres:5432/cs2_analysis
      - REDIS_URL=redis://redis:6379
      - QDRANT_URL=http://qdrant:6333
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - CARGO_INCREMENTAL=1
    depends_on:
      - postgres
      - redis
      - qdrant
    networks:
      - cs2-dev-network
    stdin_open: true
    tty: true
    restart: unless-stopped

  # =============================================================================
  # Database Services
  # =============================================================================
  postgres:
    image: postgres:15-alpine
    container_name: cs2-dev-postgres
    environment:
      - POSTGRES_DB=cs2_analysis
      - POSTGRES_USER=cs2user
      - POSTGRES_PASSWORD=cs2pass
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    networks:
      - cs2-dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cs2user -d cs2_analysis"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cs2-dev-redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-dev-data:/data
    ports:
      - "6379:6379"
    networks:
      - cs2-dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # =============================================================================
  # Vector Database & Search
  # =============================================================================
  qdrant:
    image: qdrant/qdrant:latest
    container_name: cs2-dev-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-dev-data:/qdrant/storage
      - ./.devcontainer/qdrant-config.yaml:/qdrant/config/production.yaml:ro
    networks:
      - cs2-dev-network
    restart: unless-stopped
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

  # =============================================================================
  # Monitoring & Observability (Optional for development)
  # =============================================================================
  grafana:
    image: grafana/grafana:latest
    container_name: cs2-dev-grafana
    ports:
      - "3001:3000"  # Changed to avoid conflict with frontend
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - grafana-dev-data:/var/lib/grafana
      - ./.devcontainer/grafana:/etc/grafana/provisioning:ro
    networks:
      - cs2-dev-network
    restart: unless-stopped
    profiles:
      - monitoring

  # =============================================================================
  # MinIO for object storage (S3 compatible for local development)
  # =============================================================================
  minio:
    image: minio/minio:latest
    container_name: cs2-dev-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-dev-data:/data
    networks:
      - cs2-dev-network
    restart: unless-stopped
    profiles:
      - storage

# =============================================================================
# Networks and Volumes
# =============================================================================
networks:
  cs2-dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres-dev-data:
  redis-dev-data:
  qdrant-dev-data:
  grafana-dev-data:
  minio-dev-data:
  cargo-cache:
  target-cache:
