services:
  # PostgreSQL + TimescaleDB for relational and time-series data
  postgres:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_DB: cs2_analysis
      POSTGRES_USER: cs2_user
      POSTGRES_PASSWORD: cs2_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c shared_preload_libraries=timescaledb
    restart: unless-stopped

  # Qdrant Vector Database for behavioral embeddings
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__API_KEY: "1234"
    restart: unless-stopped

  # Redis for caching and job queues
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Garage (S3-compatible object storage) — single node
  garage:
    image: dxflrs/garage:v2.0.0
    container_name: garage
    command: [ "/garage", "-c", "/etc/garage/config.toml", "server" ]
    ports:
      - "3900:3900" # S3 API
      - "3901:3901" # RPC
      - "3903:3903" # Admin API
    volumes:
      - ./garage/config.toml:/etc/garage/config.toml:ro
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data
      - garage_etc:/etc/garage
    healthcheck:
      # Use exec (no shell inside the image)
      test: [ "CMD", "/garage", "-c", "/etc/garage/config.toml", "status" ]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  postgres_data:
  qdrant_data:
  redis_data:
  garage_meta:
  garage_data:
  garage_etc: