[package]
name = "cs2-common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bytemuck = { version = "1.14", features = ["derive"] }
thiserror = "2.0"
anyhow = "1.0"

[dev-dependencies]
rstest = "0.26"
serde_json = "1.0"
