# Cargo configuration for macOS with pyenv
[target.'cfg(target_os = "macos")']
# Use dynamic lookup for Python symbols
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup"
]

# Set environment variables for PyO3
[env]
# Set Python executable
PYO3_PYTHON = "/Users/christian.klat/.pyenv/versions/3.9.16/bin/python3"
# Set PYTHONPATH
PYTHONPATH = "/Users/christian.klat/.pyenv/versions/3.9.16/lib/python3.9"
# Tell PyO3 to ignore Python version mismatches
PYO3_PYTHON_VERSION = "3.9"
# Bypass some version checks
BINDGEN_EXTRA_CLANG_ARGS = "-I/Users/christian.klat/.pyenv/versions/3.9.16/include/python3.9"
MACOSX_DEPLOYMENT_TARGET = "11.0"
